version: '3'
services:
  db:
    container_name: pg_graphql_test_db
    build:
        context: .
        dockerfile: ./dockerfiles/db/Dockerfile
    ports:
      - 5402:5432
    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - shared_preload_libraries=pg_stat_statements
    healthcheck:
      test: ["CMD-SHELL", "PGUSER=postgres", "pg_isready"]
      interval: 1s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gqldb
